### PR TITLE
Fix build on Qt 6.7 Qt 6.8 on openSUSE

### PR DESCRIPTION
**Pull request by zccrs**

### CODE REVIEW

**Comment by wineee** [comment]
Build on archlinux  ci were not successful

**Comment by hillwoodroc** [comment]
New error:

[   39s] /home/abuild/rpmbuild/BUILD/waylib-0.1.1/src/server/kernel/wtexture.cpp:50:42: error: invalid cast from type ‘VkImage’ {aka ‘long long unsigned int’} to type ‘quintptr’ {aka ‘unsigned int’}
[   39s]    50 |                                          reinterpret_cast<quintptr>(attribs.image),
[   39s]       |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   39s] make[2]: *** [src/server/CMakeFiles/waylibserver.dir/build.make:225: src/server/CMakeFiles/waylibserver.dir/kernel/wtexture.cpp.o] Error 1
[   39s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/waylib-0.1.1/build'
[   39s] make[2]: *** Waiting for unfinished jobs....
[   41s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/waylib-0.1.1/build'

**Comment by zccrs** [comment]
> New error:
> 
> [ 39s] /home/abuild/rpmbuild/BUILD/waylib-0.1.1/src/server/kernel/wtexture.cpp:50:42: error: invalid cast from type ‘VkImage’ {aka ‘long long unsigned int’} to type ‘quintptr’ {aka ‘unsigned int’} [ 39s] 50 | reinterpret_cast(attribs.image), [ 39s] | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [ 39s] make[2]: *** [src/server/CMakeFiles/waylibserver.dir/build.make:225: src/server/CMakeFiles/waylibserver.dir/kernel/wtexture.cpp.o] Error 1 [ 39s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/waylib-0.1.1/build' [ 39s] make[2]: *** Waiting for unfinished jobs.... [ 41s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/waylib-0.1.1/build'

try `static_cast`

**Comment by hillwoodroc** [comment]
It works!

**Review by wineee — APPROVED** [review]
