### ISSUE TITLE
failed to compile with clang (15.0.6)

### ISSUE THREAD

**Issue by YukariChiba** [vioken/waylib#174]
Example:

```
 /usr/src/packages/BUILD/waylib/src/waylib/src/server/qtquick/woutputhelper.cpp:446:5: error: attempt to use a deleted function
     delete texture;
     ^
 /usr/include/qwlroots/qwtexture.h:21:5: note: '~QWTexture' has been explicitly marked deleted here
     ~QWTexture() = delete;
     ^
```

**Comment by wineee** [comment]
We use destroying operator delete in C++20, to avoid call the destructor of c++ Class (QWTexture) when call delete, the data will be destroyed in c language (wlroots).

https://clang.llvm.org/cxx_status.htmlclang support this feature  [P0722R3](https://wg21.link/p0722r3)  since 6.0

But now it is still required that the destructor exists, which should be related to the compiler implementation...

You need patch qwlroots,  remove `~QWTexture() = delete;`
